### ISSUE TITLE
Standard login credentials after fresh install

### ISSUE THREAD

**Issue by jenniferawesome** [OpenSILEX/phis-webapp#113]
Hi,

I just ran a fresh install of the installation but what are the credentials/admin credentials to login the first time? for the webfront end of PHIS.

Kind regards,

**Comment by pierreetiennealary** [comment]
Hi,

the credentials used are the ones provided in the https://github.com/OpenSILEX/docs-community-dev/blob/master/docs/assets/phis_st_dump.sql file. Additional users should be added modifying this file (on line 331) previous to Phis installation, you will then be the one setting the passwords of those new users/accounts.

Best regards
